### ISSUE TITLE
Home/Responsive Issue

### ISSUE THREAD

**Issue by asif-mahmood-com** [asif-mahmood-com/markhamrollins#1]
on re sizing text goes behind the logo.
Need to check this issue in all browsers
opera http://prntscr.com/m5rvqs
firefox http://prntscr.com/m5rwvm
chrome http://prntscr.com/m5rxbs
ie 11 http://prntscr.com/m5rxs8
safari http://prntscr.com/m5s37x

**Comment by Sajid-Ali-com** [comment]
Fixed all points.

**Comment by asif-mahmood-com** [comment]
Old Bugs
